version: '3.6'

volumes:
  shared-file-store:
    driver_opts:
      type: tmpfs
      device: tmpfs

services:
  alfresco:
    image: ${DOCKER_IMAGE_PREFIX}alfresco
    volumes:
      - ${VOLUME_ALFRESCO_REPO_DATA}:/usr/local/tomcat/alf_data:cached
    depends_on:
      - activemq
      - search
      - service-sync
      - transform-core-aio
      - transform-router
    environment:
      JAVA_TOOL_OPTIONS: "
        -Dencryption.keystore.type=JCEKS
        -Dencryption.cipherAlgorithm=DESede/CBC/PKCS5Padding
        -Dencryption.keyAlgorithm=DESede
        -Dencryption.keystore.location=/usr/local/tomcat/shared/classes/alfresco/extension/keystore/keystore
        -Dmetadata-keystore.password=mp6yc0UD9e
        -Dmetadata-keystore.aliases=metadata
        -Dmetadata-keystore.metadata.password=oKIWzVdEdA
        -Dmetadata-keystore.metadata.algorithm=DESede
        "
      JAVA_OPTS: "
        -Ddb.driver=${ACS_DATABASE_DRIVER}
        -Ddb.url=${ACS_DATABASE_JDBC_URL}
        -Ddb.username=${ACS_DATABASE_USER}
        -Ddb.password=${ACS_DATABASE_PASSWORD}
        -Dsolr.host=search
        -Dsolr.port=8983
        -Dsolr.secureComms=secret
        -Dsolr.sharedSecret=secret
        -Dsolr.base.url=/solr
        -Dindex.subsystem.name=solr6
        -Dalfresco.host=${PROXY_HOST}
        -Dalfresco.port=${PROXY_PORT}
        -Dalfresco.protocol=${PROXY_PROTOCOL}
        -Dalfresco.context=alfresco
        -Dshare.host=${PROXY_HOST}
        -Dshare.port=${PROXY_PORT}
        -Dshare.protocol=${PROXY_PROTOCOL}
        -Dshare.context=share
        -Daos.baseUrlOverwrite=${PROXY_PROTOCOL}://${PROXY_HOST}:${PROXY_PORT}/alfresco/aos
        -Dmessaging.broker.url=\"failover:(nio://activemq:61616)?timeout=3000&jms.useCompression=true\"
        -Ddsync.service.uris=http://service-sync:9090/alfresco/
        -Ddeployment.method=DOCKER_COMPOSE
        -Dcsrf.filter.enabled=false
        -Dtransform.service.enabled=true
        -Dlocal.transform.service.enabled=true
        -Dlegacy.transform.service.enabled=true
        -Dtransform.service.url=http://transform-router:8095
        -DlocalTransform.core-aio.url=http://transform-core-aio:8090/
        -Dalfresco-pdf-renderer.url=http://transform-core-aio:8090/
        -Djodconverter.url=http://transform-core-aio:8090/
        -Dimg.url=http://transform-core-aio:8090/
        -Dtika.url=http://transform-core-aio:8090/
        -Dtransform.misc.url=http://transform-core-aio:8090/
        -Dsfs.url=http://shared-file-store:8099/
        -Dalfresco.restApi.basicAuthScheme=true
        -Dauthentication.chain=alfinst:alfrescoNtlm,${LDAP_CONFIG}:${LDAP_AUTH_MODULE}
        -Dntlm.authentication.sso.enabled=false
        ${JVM_MEM_ALFRESCO_REPO}
        ${JVM_DEBUG}"
      LDAP_CONFIG: ${LDAP_CONFIG}
      LDAP_AUTH_MODULE: ${LDAP_AUTH_MODULE}
      LDAP_URL: ${LDAP_URL}
      LDAP_USER: ${LDAP_USER}
      LDAP_PASSWORD: ${LDAP_PASSWORD}
      SERVER_MODE: ${SERVER_MODE}

  activemq:
    image: alfresco/alfresco-activemq:${ALFRESCO_ACTIVEMQ_VERSION}

  search:
    image: alfresco/alfresco-search-services:${ALFRESCO_SEARCH_VERSION}
    volumes:
      - ${VOLUME_ALFRESCO_SEARCH_DATA}:/opt/alfresco-search-services/data:cached
    environment:
      SOLR_JAVA_MEM: "${JVM_MEM_ALFRESCO_SEARCH}"
      SOLR_ALFRESCO_HOST: "alfresco"
      SOLR_ALFRESCO_PORT: "8080"
      SOLR_SOLR_HOST: "search"
      SOLR_SOLR_PORT: "8983"
      SOLR_CREATE_ALFRESCO_DEFAULTS: "alfresco,archive"
      ALFRESCO_SECURE_COMMS: "secret"
      JAVA_TOOL_OPTIONS: "
        -Dalfresco.secureComms.secret=secret"

  service-sync:
    image: quay.io/alfresco/service-sync:${ALFRESCO_SERVICE_SYNC_VERSION}
    depends_on:
      - activemq
    environment:
      JAVA_OPTS: "
        -Dsql.db.driver=${ACS_DATABASE_DRIVER}
        -Dsql.db.url=${ACS_DATABASE_JDBC_URL}
        -Dsql.db.username=${ACS_DATABASE_USER}
        -Dsql.db.password=${ACS_DATABASE_PASSWORD}
        -Dmessaging.broker.host=activemq
        -Drepo.hostname=alfresco
        -Drepo.port=8080
        -Ddw.server.applicationConnectors[0].type=http
        ${JVM_MEM_ALFRESCO_SERVICE_SYNC}"

  shared-file-store:
    image: quay.io/alfresco/alfresco-shared-file-store:${ALFRESCO_SHARED_FILE_STORE_VERSION}
    volumes:
      - shared-file-store:/tmp/Alfresco/sfs
    environment:
      JAVA_OPTS: "${JVM_MEM_ALFRESCO_SHARED_FILE_STORE}"
      scheduler.content.age.millis: 86400000
      scheduler.cleanup.interval: 86400000

  transform-core-aio:
    image: alfresco/alfresco-transform-core-aio:${ALFRESCO_TRANSFORM_CORE_AIO_VERSION}
    depends_on:
      - activemq
      - shared-file-store
    environment:
      JAVA_OPTS: "${JVM_MEM_ALFRESCO_TRANSFORM_CORE_AIO}"
      ACTIVEMQ_URL: "nio://activemq:61616"
      FILE_STORE_URL: "http://shared-file-store:8099/alfresco/api/-default-/private/sfs/versions/1/file"

  transform-router:
    image: quay.io/alfresco/alfresco-transform-router:${ALFRESCO_TRANSFORM_ROUTER_VERSION}
    depends_on:
      - activemq
      - shared-file-store
      - transform-core-aio
    environment:
      JAVA_OPTS: "${JVM_MEM_ALFRESCO_TRANSFORM_ROUTER}"
      ACTIVEMQ_URL: "nio://activemq:61616"
      CORE_AIO_URL: "http://transform-core-aio:8090"
      FILE_STORE_URL: "http://shared-file-store:8099/alfresco/api/-default-/private/sfs/versions/1/file"
