name: Docker Image CI

on:
  workflow_dispatch:

jobs:
  maven:
    uses: ./.github/workflows/maven.yml
    secrets: inherit
    with:
      uploadArtifacts: true
  docker:
    needs: maven
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        with:
          name: artifacts
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1
      - name: Login to AWS ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
      - name: Build and push Docker images
        env:
          QUAY_IO_USERNAME: ${{ secrets.QUAY_IO_USERNAME }}
          QUAY_IO_PASSWORD: ${{ secrets.QUAY_IO_PASSWORD }}
        run: docker/ci/build-and-push.sh